### ISSUE TITLE
Can't deploy to Vercel, failed to complete

### ISSUE THREAD

**Issue by jawadan** [graphcommerce-org/graphcommerce#1807]
### Describe the Bug

**I wasn't able to deploy it to vercel, nor build locally. Throws this error:**

info  - Skipping linting
info  - Checking validity of types...
Failed to compile.
./node_modules/@graphcommerce/graphcms-ui/links/createHygraphLink.ts:11:14
Type error: Argument of type '(_: GraphQLRequest<Record<string, any>>, context: ClientContext) => ClientContext' is not assignable to parameter of type 'ContextSetter'.
  Types of parameters 'context' and 'prevContext' are incompatible.
    Type 'DefaultContext' is not assignable to type 'ClientContext'.
   9 |  */
  10 | export const createHygraphLink = (locale?: string) =>
> 11 |   setContext((_, context: ClientContext) => {
     |              ^
  12 |     if (!context.headers) context.headers = {}
  13 | 
  14 |     const gcmsLocales = [
> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/vercel/path0/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/vercel/path0/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

### Expected Behavior

**Here is the example of my Environment Variables:**

GRAPHCMS_URL | https://example/master

MAGENTO_ENDPOINT | https://backend.reachdigital.dev/graphql

NEXT_PUBLIC_GRAPHQL_ENDPOINT | http://example.vercel.app/api/graphql

NEXT_PUBLIC_SITE_URL | https://example.vercel.app/

IMAGE_DOMAINS | backend.reachdigital.dev,media.graphcms.com,media.graphassets.com

NEXT_PUBLIC_LOCALE_STORES | {"en-us": "en_US", "nl": "nl_NL", "fr-be": "fr_BE", "nl-be": "nl_BE", "en-gb": "en_GB", "en-ca": "en_CA"}

NEXT_PUBLIC_DISPLAY_INCL_TAX | nl,fr-be,nl-be,en-gb,eu

### To Reproduce

**Went through all configuration steps explained in README.me:**

1. `git clone -b main --depth 1 https://github.com/graphcommerce-org/graphcommerce.git`
2. `mkdir my-project`
3. `cp -R graphcommerce/examples/magento-graphcms/. my-project`
4. `cd my-project`
5. `cp -R .env.example .env`
6. `rm CHANGELOG.md`
7. `rm -r node_modules && rm -r .next`
- `yarn` Install the dependencies
- `yarn codegen` Converts all .graphql files to typescript files
- `yarn dev` Run the app

"yarn dev" works just fine, but wasn't able to build it.

**Comment by paales** [comment]
We’ve got an issue where some dependencies (@lingui/* and @apollo/client) are automatically installing a newer version which break the build. To solve the issue, add the following to your package.json:

```
  "resolutions": {
    "@apollo/client": "3.7.2",
    "@lingui/cli": "3.15.0",
    "@lingui/core": "3.15.0",
    "@lingui/react": "3.15.0",
    "@lingui/conf": "3.15.0",
    "@lingui/babel-plugin-extract-messages": "3.15.0"
  },
```

This is solved in the new GraphCommerce release.

**Comment by jawadan** [comment]
Thank you very much. It worked!

**Comment by jawadan** [comment]
How could I possibly tryout the latest release?
