### ISSUE TITLE
Magento 2.4.6 doesn't work with GC

### ISSUE THREAD

**Issue by wmycco1** [graphcommerce-org/graphcommerce#2154]
### Describe the Bug

I decided to try to install my magento 2.4.6, which has been working stably for a long time in the local ubuntu 20.04 environment.

In the file /var/www/mygraphcommerce.com/my-project/graphcommerce.config.js:

```
const config = {
  hygraphEndpoint: 'https://eu-central-1.cdn.hygraph.com/content/ckhx7xadya6xs01yxdujt8i80/master',
  magentoEndpoint: 'https://test.mag.com/graphql',
  canonicalBaseUrl: 'https://test.mag.com',
  storefront: [{ locale: 'en', magentoStoreCode: 'en_US' }],
}
```

module.exports = config

**Here are the errors in the console:**

```
planet@eng-kt:/var/www/mygraphcommerce.com/my-project$ yarn codegen
yarn run v1.22.19
$ graphcommerce codegen-config && mesh build && graphql-codegen
💡 🕸️  Mesh Cleaning existing artifacts
💡 🕸️  Mesh Reading the configuration
💡 🕸️  Mesh Generating the unified schema
💥 🕸️  Mesh - m2 Failed to generate the schema Error: Failed to fetch introspection from https://test.mag.com/graphql: TypeError: Cannot read properties of undefined (reading '__schema')
    at /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/graphql/cjs/index.js:149:36
    at async Object.getWithSet (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/store/cjs/index.js:174:38)
    at async Promise.allSettled (index 0)
    at async GraphQLHandler.getMeshSourceWithoutFederation (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/graphql/cjs/index.js:379:52)
    at async GraphQLHandler.getMeshSource (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/graphql/cjs/index.js:244:28)
    at async /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:118:28
    at async Promise.allSettled (index 1)
    at async getMesh (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:113:5)
    at async Object.handler (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/cli/cjs/index.js:337:53)
    at GraphQLHandler.getMeshSourceWithoutFederation (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/graphql/cjs/index.js:387:23)
    at async GraphQLHandler.getMeshSource (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/graphql/cjs/index.js:244:28)
    at async /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:118:28
    at async Promise.allSettled (index 1)
    at async getMesh (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:113:5)
    at async Object.handler (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/cli/cjs/index.js:337:53)
💥 🕸️  Mesh Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
    at getMesh (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:152:15)
    at async Object.handler (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-mesh/cli/cjs/index.js:337:53)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
planet@eng-kt:/var/www/mygraphcommerce.com/my-project$ yarn dev
yarn run v1.22.19
$ concurrently -k -n codegen,next 'graphql-codegen -w' 'next dev'
[codegen] [STARTED] Parse Configuration
[codegen] [SUCCESS] Parse Configuration
[codegen] [STARTED] Generate outputs
[codegen] [STARTED] Generate to node_modules/@graphcommerce/graphql/generated/types.ts
[codegen] [STARTED] Generate to node_modules/@graphcommerce/graphql/generated/fragments.json
[codegen] [STARTED] Generate to .
[codegen] [STARTED] Generate to node_modules/@graphcommerce
[codegen] [STARTED] Load GraphQL schemas
[codegen] [STARTED] Load GraphQL schemas
[codegen] [STARTED] Load GraphQL schemas
[codegen] [STARTED] Load GraphQL schemas
[codegen] [FAILED] 
[codegen] [FAILED]         Failed to load schema from .mesh/schema.graphql:
[codegen] [FAILED] 
[codegen] [FAILED]         
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]         Error: 
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]     at prepareResult (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:82:15)
[codegen] [FAILED]     at loadTypedefs (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:40:20)
[codegen] [FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/schema.js:15:21)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/load.js:36:24)
[codegen] [FAILED]     at async /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/codegen.js:190:69
[codegen] [FAILED] 
[codegen] [FAILED]         GraphQL Code Generator supports:
[codegen] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[codegen] [FAILED]           - Introspection JSON File
[codegen] [FAILED]           - URL of GraphQL endpoint
[codegen] [FAILED]           - Multiple files with type definitions (glob expression)
[codegen] [FAILED]           - String in config file
[codegen] [FAILED] 
[codegen] [FAILED]         Try to use one of above options and run codegen again.
[codegen] [FAILED] 
[codegen] [FAILED]       
[codegen] [FAILED] 
[codegen] [FAILED]         Failed to load schema from .mesh/schema.graphql:
[codegen] [FAILED] 
[codegen] [FAILED]         
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]         Error: 
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]     at prepareResult (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:82:15)
[codegen] [FAILED]     at loadTypedefs (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:40:20)
[codegen] [FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/schema.js:15:21)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/load.js:36:24)
[codegen] [FAILED]     at async /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/codegen.js:190:69
[codegen] [FAILED] 
[codegen] [FAILED]         GraphQL Code Generator supports:
[codegen] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[codegen] [FAILED]           - Introspection JSON File
[codegen] [FAILED]           - URL of GraphQL endpoint
[codegen] [FAILED]           - Multiple files with type definitions (glob expression)
[codegen] [FAILED]           - String in config file
[codegen] [FAILED] 
[codegen] [FAILED]         Try to use one of above options and run codegen again.
[codegen] [FAILED] 
[codegen] [FAILED]       
[codegen] [FAILED] 
[codegen] [FAILED]         Failed to load schema from .mesh/schema.graphql:
[codegen] [FAILED] 
[codegen] [FAILED]         
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]         Error: 
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]     at prepareResult (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:82:15)
[codegen] [FAILED]     at loadTypedefs (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:40:20)
[codegen] [FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/schema.js:15:21)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/load.js:36:24)
[codegen] [FAILED]     at async /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/codegen.js:190:69
[codegen] [FAILED] 
[codegen] [FAILED]         GraphQL Code Generator supports:
[codegen] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[codegen] [FAILED]           - Introspection JSON File
[codegen] [FAILED]           - URL of GraphQL endpoint
[codegen] [FAILED]           - Multiple files with type definitions (glob expression)
[codegen] [FAILED]           - String in config file
[codegen] [FAILED] 
[codegen] [FAILED]         Try to use one of above options and run codegen again.
[codegen] [FAILED] 
[codegen] [FAILED]       
[codegen] [FAILED] 
[codegen] [FAILED]         Failed to load schema from .mesh/schema.graphql:
[codegen] [FAILED] 
[codegen] [FAILED]         
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]         Error: 
[codegen] [FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[codegen] [FAILED]         
[codegen] [FAILED]           - .mesh/schema.graphql
[codegen] [FAILED]           
[codegen] [FAILED]     at prepareResult (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:82:15)
[codegen] [FAILED]     at loadTypedefs (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/load-typedefs.js:40:20)
[codegen] [FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-tools/load/cjs/schema.js:15:21)
[codegen] [FAILED]     at async loadSchema (/var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/load.js:36:24)
[codegen] [FAILED]     at async /var/www/mygraphcommerce.com/my-project/node_modules/@graphql-codegen/cli/cjs/codegen.js:190:69
[codegen] [FAILED] 
[codegen] [FAILED]         GraphQL Code Generator supports:
[codegen] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[codegen] [FAILED]           - Introspection JSON File
[codegen] [FAILED]           - URL of GraphQL endpoint
[codegen] [FAILED]           - Multiple files with type definitions (glob expression)
[codegen] [FAILED]           - String in config file
[codegen] [FAILED] 
[codegen] [FAILED]         Try to use one of above options and run codegen again.
[codegen] [FAILED] 
[codegen] [FAILED]       
[codegen] [SUCCESS] Generate outputs
[codegen]   ℹ Watching for changes in /var/www/mygraphcommerce.com/my-project...
[next] - warn You have enabled experimental features (scrollRestoration, swcPlugins) in next.config.js.
[next] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[next] 
[next] - ready started server on [::]:3000, url: http://localhost:3000
[next] - info (pwa) PWA support is disabled.
[next] - info (pwa) PWA support is disabled.
[next] - event compiled client and server successfully in 4.7s
[next] - wait compiling...
[next] - event compiled client and server successfully in 4.2s
[next] - wait compiling /api/graphql (client and server)...
[next] - wait compiling /[...url] (client and server)...
[next] - wait compiling / (client and server)...
[next] - error ./node_modules/@graphcommerce/graphql-mesh/.mesh.ts:1:0
[next] Module not found: Can't resolve '../../../.mesh'
[next] 
[next] https://nextjs.org/docs/messages/module-not-found
[next] 
[next] Import trace for requested module:
[next] ./node_modules/@graphcommerce/graphql-mesh/index.ts
[next] ./lib/graphql/graphqlSsrClient.ts
[next] ./pages/[...url].tsx
[next] - wait compiling /_error (client and server)...
[next] - error ./node_modules/@graphcommerce/graphql-mesh/.mesh.ts:1:0
[next] Module not found: Can't resolve '../../../.mesh'
[next] 
[next] https://nextjs.org/docs/messages/module-not-found
[next] 
[next] Import trace for requested module:
[next] ./node_modules/@graphcommerce/graphql-mesh/index.ts
[next] ./lib/graphql/graphqlSsrClient.ts
[next] ./pages/[...url].tsx
[next] - warn Fast Refresh had to perform a full reload due to a runtime error.
[next] <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/var/www/mygraphcommerce.com/my-project/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/var/www/mygraphcommerce.com/my-project/.next/cache/webpack/client-development-fallback/0.pack.gz'
[next] <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/var/www/mygraphcommerce.com/my-project/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/var/www/mygraphcommerce.com/my-project/.next/cache/webpack/client-development-fallback/0.pack.gz'
[next] <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/var/www/mygraphcommerce.com/my-project/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/var/www/mygraphcommerce.com/my-project/.next/cache/webpack/client-development-fallback/0.pack.gz'
```

**And here's what's in google chrome:**
./node_modules/@graphcommerce/graphcms-ui/graphql/index.ts:1:0
Module not found: Can't resolve './HygraphAllPages.gql'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@graphcommerce/graphcms-ui/index.ts
./node_modules/@graphcommerce/graphcms-ui/index.interceptor.tsx
./pages/index.tsx

### Expected Behavior

When specifying my data in the magento Endpoint and canonicalBaseUrl lines in the frontend, my data from my magento 2.4.6 should be displayed

### To Reproduce

I also tried running NODE_TLS_REJECT_UNAUTHORIZED=0 yarn codegen and NODE_TLS_REJECT_UNAUTHORIZED=0 yarn dev but without success
I also checked the work of graphql in magento 2 via postman,everything is fine there
I have node 18 installed

**Comment by HungDo-Niteco** [comment]
@wmycco1 I've had this issue before, https://github.com/graphcommerce-org/graphcommerce/issues/2080#issuecomment-1788547654

**Comment by paales** [comment]
The line:

```
💥 🕸️  Mesh - m2 Failed to generate the schema Error: Failed to fetch introspection from https://test.mag.com/graphql: TypeError: Cannot read properties of undefined (reading '__schema')
```

Indicates that the GraphQL Mesh is unable to connect to a valid (Magento 2) endpoint. This can be due to SSL issues / or http auth or something similar.

When you open the endpoint in your browser, do you see the same result at seen here: https://backend.reachdigital.dev/graphql (indicating that you haven't send any GraphQL document)

**Comment by magecommerce** [comment]
doest the magento 2 server side need install any extension ?

**Comment by paales** [comment]
@magecommerce It should work out of the box.
