### ISSUE TITLE
Generating the unified schema fails

### ISSUE THREAD

**Issue by softcommerceltd** [graphcommerce-org/graphcommerce#2311]
### Describe the Bug

Execution of `yarn codegen` throws the following error.

 ✘ yarn codegen
🕸️  Mesh 💡 Cleaning existing artifacts
🕸️  Mesh 💡 Reading the configuration
🕸️  Mesh 💡 Generating the unified schema
Unable to write file "/home/softcom/graphcommerce/gc-8.1.0-canary.42/.mesh/sources/hygraph/introspectionSchema.ts". This might cause an inconsistency. /home/softcom/graphcommerce/gc-8.1.0-canary.42/.mesh/sources/hygraph/introspectionSchema.ts:2
import { buildASTSchema } from 'graphql';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/softcom/graphcommerce/gc-8.1.0-canary.42/node_modules/@graphql-mesh/utils/cjs/defaultImportFn.js:29:74
    at async defaultImportFn (/home/softcom/graphcommerce/gc-8.1.0-canary.42/node_modules/@graphql-mesh/utils/cjs/defaultImportFn.js:29:18)
Unable to write file "/home/softcom/graphcommerce/gc-8.1.0-canary.42/.mesh/sources/m2/introspectionSchema.ts". This might cause an inconsistency. /home/softcom/graphcommerce/gc-8.1.0-canary.42/.mesh/sources/m2/introspectionSchema.ts:2
import { buildASTSchema } from 'graphql';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/softcom/graphcommerce/gc-8.1.0-canary.42/node_modules/@graphql-mesh/utils/cjs/defaultImportFn.js:29:74
    at async defaultImportFn (/home/softcom/graphcommerce/gc-8.1.0-canary.42/node_modules/@graphql-mesh/utils/cjs/defaultImportFn.js:29:18)
🕸️  Mesh 💡 Generating artifacts
🕸️  Mesh 💡 Generating index file in TypeScript
🕸️  Mesh 💡 Writing index.ts for ESM to the disk.
🕸️  Mesh 💡 Cleanup
🕸️  Mesh 💡 Done! => /home/softcom/graphcommerce/gc-8.1.0-canary.42/.mesh
✔ Parse Configuration
✔ Generate outputs

### Expected Behavior

Execution of `yarn codegen` should run successfully.

### To Reproduce

Run `yarn codegen` to reproduce the error.

Tested with the following
- Ubuntu 23.10
- Node.js v20.15.0
- Yarn 4.1.1
- GC latest pre-release 8.1.0-canary.42

Also tested on MacOS
- MacOs 14.4.1 [build: 23E224]
- Node.js v20.15.0
- Yarn 4.1.1
- GC latest pre-release 8.1.0-canary.42

**Comment by softcommerceltd** [comment]
I notice you are working on this as per discussion in
https://graphcommerce.slack.com/archives/C02K7SJNCLB/p1719995196477569?thread_ts=1719933445.732429&cid=C02K7SJNCLB

**Comment by paales** [comment]
This is the fix: https://github.com/graphcommerce-org/graphcommerce/commit/6184a28b2ba2dc70189a9b881887696dc0a346c8
